version: "3"
services: 
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: j-test
        tty: true
        volumes: 
            - .:/app
        ports: 
            - 8080:8080